### ISSUE TITLE
Icons not working?

### ISSUE THREAD

**Issue by philippe-a-kimoby** [mdelmage/ladder#11]
We created icons (:ladder_2000:, :ladder_1950: etc...) and the icons are still the default gray square. Do we need to run a command for the bot to use the correct icons or am I missing something?

Thanks for the help, great bot 👍

**Comment by mdelmage** [comment]
Hi Phillipe,

You are correct. There is an issue with the OAuth permissions that prevents the bot from updating the database with your icon names.

I can help resolve this for you manually if you send your Team ID to matt@delmageconsulting.com. The easiest way I find to retrieve the Team ID is to pull the URL of your avatar image -- for example mine is https://ca.slack-edge.com/T02G6Q28RMK-U02G32KJ0DC-2649d0b200b8-512. Team ID is the "T02..." and User ID is the "U02..." part.

Thanks --
Matt
