### ISSUE TITLE
Added custom emoji, but ladder still displays :white_medium_square: for all levels

### ISSUE THREAD

**Issue by derekhardwick** [mdelmage/ladder#5]
I think I've set this up, but maybe I made an obvious mistake.

<img width="938" alt="Screen Shot 2020-01-10 at 12 05 55" src="https://user-images.githubusercontent.com/1249644/72148650-9f162000-33a1-11ea-9093-1ff59781f20e.png">
<img width="465" alt="Screen Shot 2020-01-10 at 12 06 09" src="https://user-images.githubusercontent.com/1249644/72148653-a0474d00-33a1-11ea-9dae-723dc6870ddb.png">

**Comment by clarkd** [comment]
See https://github.com/mdelmage/ladder/issues/3

You need to type `/ladder emoji` to update the set. 👍

**Comment by derekhardwick** [comment]
Sweet thanks!

Ninja-edit: Oh you may want to add that to the emoji section of the site (and/or /ladder help)!
